name: Node CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Postgres via service container
        uses: harmon758/postgres-action@v1.4
        with:
          postgresql version: "15"
          postgresql db: "sweetshop"
          postgresql user: "sweetuser"
          postgresql password: "sweetpass"
      - name: Install backend deps and run tests
        run: |
          cd backend
          npm ci
          npx prisma generate
          npx prisma migrate deploy || true
          npm test
